all:
	gcc -o eserver echo_selectserv.c 
	gcc -o eclient echo_client.c
	gcc -o stdcpy stdcpy.c
	gcc -o syscpy syscpy.c
	gcc -o desto desto.c
	gcc -o dup dup.c
	gcc -o serv2 sep_serv2.c
	gcc -o clnt sep_clnt.c
