all:
	gcc -pthread -o thread1 thread1.c
	gcc -pthread -o thread2 thread2.c
	gcc -pthread -o thread3 thread3.c
	gcc -pthread -D_REENTRANT -o mutex mutex.c
	gcc -pthread -D_REENTRANT -o semaphore semaphore.c
	gcc -pthread -D_REENTRANT -o client chat_clnt.c
	gcc -pthread -o server chat_serv.c






	
