all:
	gcc fork.c -o fork
	gcc zombie.c -o zombie
	gcc wait.c -o wait
	gcc waitpid.c -o waitpid
	gcc signal.c -o signal
	gcc sigaction.c -o sigaction
	gcc remove_zombie.c -o r_zombie
	gcc echo_mpserv.c -o server
	gcc echo_mpclient.c -o client

